#!/usr/bin/env python3
"""Refresh the `integration-version` dropdown in the bug-report issue form.

GitHub issue forms can't pull dropdown options from releases dynamically, so
this script regenerates the option list from `gh release list` and rewrites
the block between the AUTOGENERATED sentinels in `bug_report.yml`. Run by
`.github/workflows/update-version-dropdown.yml` on every published release.

Only the lines between the sentinels are touched — the surrounding form
(including the permanent "Other / not listed" escape hatch that lives after
the END sentinel) is left byte-for-byte intact.
"""

from __future__ import annotations

import json
import pathlib
import subprocess

TEMPLATE = pathlib.Path(".github/ISSUE_TEMPLATE/bug_report.yml")
BEGIN = "# BEGIN AUTOGENERATED VERSIONS"
END = "# END AUTOGENERATED VERSIONS"

# How far back to look when deciding what to offer.
FETCH = 100
# Newest releases of any kind, so whoever is on the current beta finds it.
RECENT_ANY = 8
# Newest *stable* releases. Kept separately because a flat "newest N" window
# does not serve the people most likely to file a bug: this project ships
# betas in long runs (twelve for 1.15.1, six for 1.16.0), so a flat window of
# 15 held exactly one stable out of the 38 published, and every HACS user who
# had not opted into betas had to pick "Other / not listed". That is not
# cosmetic — an unusable dropdown is why #372 could not be diagnosed, because
# the reporter's build was unknown and the fix he needed had shipped in a
# specific version.
RECENT_STABLE = 14


def _releases() -> list[dict[str, object]]:
    result = subprocess.run(
        [
            "gh",
            "release",
            "list",
            "--limit",
            str(FETCH),
            "--json",
            "tagName,isPrerelease",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    return list(json.loads(result.stdout or "[]"))


def recent_versions() -> list[str]:
    """Return the versions to offer, newest first, `v` stripped.

    The union of the newest releases of any kind and the newest stable ones,
    de-duplicated while preserving the API's newest-first order so the list
    still reads chronologically.
    """
    releases = _releases()
    keep: set[str] = set()
    keep.update(r["tagName"] for r in releases[:RECENT_ANY])  # type: ignore[misc]
    stables = [r for r in releases if not r["isPrerelease"]]
    keep.update(r["tagName"] for r in stables[:RECENT_STABLE])  # type: ignore[misc]

    ordered = [str(r["tagName"]) for r in releases if r["tagName"] in keep]
    return [t[1:] if t.startswith("v") else t for t in ordered]


def main() -> None:
    versions = recent_versions()
    if not versions:
        print("No releases found; leaving the template unchanged.")
        return

    text = TEMPLATE.read_text(encoding="utf-8")
    lines = text.splitlines()

    try:
        begin = next(i for i, line in enumerate(lines) if BEGIN in line)
        end = next(i for i, line in enumerate(lines) if END in line)
    except StopIteration as exc:
        raise SystemExit(
            f"Sentinels not found in {TEMPLATE}; expected '{BEGIN}' and '{END}'."
        ) from exc

    # The option items share the indentation of the sentinel comment line.
    indent = lines[begin][: lines[begin].index("#")]
    rebuilt = lines[: begin + 1] + [f"{indent}- {version}" for version in versions] + lines[end:]
    new_text = "\n".join(rebuilt) + ("\n" if text.endswith("\n") else "")

    if new_text == text:
        print("Version dropdown already up to date.")
        return

    TEMPLATE.write_text(new_text, encoding="utf-8")
    print(f"Refreshed version dropdown with {len(versions)} releases (newest: {versions[0]}).")


if __name__ == "__main__":
    main()
