# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/advanced_encryption.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/advanced_encryption.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nYsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/advanced_encryption.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\x1a\x1bgoogle/protobuf/empty.proto\"\xe4\x06\n\x16\x41\x64vancedEncryptionPart\x12\x87\x01\n\x13\x61\x64vanced_encryption\x18\x01 \x01(\x0e\x32j.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.AdvancedEncryptionPart.AdvancedEncryption\x12\x83\x01\n\x11\x61\x63tivation_status\x18\x02 \x01(\x0b\x32h.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.AdvancedEncryptionPart.ActivationStatus\x12x\n\x0c\x63\x61pabilities\x18\x03 \x03(\x0e\x32\x62.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.AdvancedEncryptionPart.Capability\x1a\xd3\x01\n\x10\x41\x63tivationStatus\x12/\n\rnot_activated\x18\x01 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x12-\n\x0bin_progress\x18\x02 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x12+\n\tactivated\x18\x03 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x12(\n\x06\x66\x61iled\x18\x04 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x42\x08\n\x06status\"|\n\x12\x41\x64vancedEncryption\x12#\n\x1f\x41\x44VANCED_ENCRYPTION_UNSPECIFIED\x10\x00\x12 \n\x1c\x41\x44VANCED_ENCRYPTION_DISABLED\x10\x01\x12\x1f\n\x1b\x41\x44VANCED_ENCRYPTION_ENABLED\x10\x02\"l\n\nCapability\x12\x1a\n\x16\x43\x41PABILITY_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x43\x41PABILITY_V2_ENCRYPTION\x10\x01\x12$\n CAPABILITY_V2_ENCRYPTION_SETTING\x10\x02\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.advanced_encryption_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_ADVANCEDENCRYPTIONPART']._serialized_start=188
  _globals['_ADVANCEDENCRYPTIONPART']._serialized_end=1056
  _globals['_ADVANCEDENCRYPTIONPART_ACTIVATIONSTATUS']._serialized_start=609
  _globals['_ADVANCEDENCRYPTIONPART_ACTIVATIONSTATUS']._serialized_end=820
  _globals['_ADVANCEDENCRYPTIONPART_ADVANCEDENCRYPTION']._serialized_start=822
  _globals['_ADVANCEDENCRYPTIONPART_ADVANCEDENCRYPTION']._serialized_end=946
  _globals['_ADVANCEDENCRYPTIONPART_CAPABILITY']._serialized_start=948
  _globals['_ADVANCEDENCRYPTIONPART_CAPABILITY']._serialized_end=1056
# @@protoc_insertion_point(module_scope)
