# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/associated_group_id.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/associated_group_id.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nYsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/associated_group_id.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\"\xb9\x05\n\x11\x41ssociatedGroupId\x12|\n\x10\x61ssociated_group\x18\x01 \x01(\x0b\x32\x62.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.AssociatedGroupId.AssociatedGroup\x12s\n\x0c\x63\x61pabilities\x18\x02 \x03(\x0e\x32].systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.AssociatedGroupId.Capability\x1a\xb4\x01\n\x19\x41ssociatedGroupIdSettings\x12\x81\x01\n\x10\x61ssociated_group\x18\x01 \x01(\x0b\x32\x62.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.AssociatedGroupId.AssociatedGroupH\x00\x88\x01\x01\x42\x13\n\x11_associated_group\x1a\xab\x01\n\x0f\x41ssociatedGroup\x12\x12\n\x08group_id\x18\x01 \x01(\tH\x00\x12u\n\x03\x61ll\x18\x02 \x01(\x0b\x32\x66.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.AssociatedGroupId.AssociatedGroup.AllH\x00\x1a\x05\n\x03\x41llB\x06\n\x04\x63\x61se\"L\n\nCapability\x12\x1a\n\x16\x43\x41PABILITY_UNSPECIFIED\x10\x00\x12\"\n\x1e\x43\x41PABILITY_ASSOCIATED_GROUP_ID\x10\x01\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.associated_group_id_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_ASSOCIATEDGROUPID']._serialized_start=226
  _globals['_ASSOCIATEDGROUPID']._serialized_end=923
  _globals['_ASSOCIATEDGROUPID_ASSOCIATEDGROUPIDSETTINGS']._serialized_start=491
  _globals['_ASSOCIATEDGROUPID_ASSOCIATEDGROUPIDSETTINGS']._serialized_end=671
  _globals['_ASSOCIATEDGROUPID_ASSOCIATEDGROUP']._serialized_start=674
  _globals['_ASSOCIATEDGROUPID_ASSOCIATEDGROUP']._serialized_end=845
  _globals['_ASSOCIATEDGROUPID_ASSOCIATEDGROUP_ALL']._serialized_start=832
  _globals['_ASSOCIATEDGROUPID_ASSOCIATEDGROUP_ALL']._serialized_end=837
  _globals['_ASSOCIATEDGROUPID_CAPABILITY']._serialized_start=847
  _globals['_ASSOCIATEDGROUPID_CAPABILITY']._serialized_end=923
# @@protoc_insertion_point(module_scope)
