# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/audio_format.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/audio_format.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nRsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/audio_format.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common*\xa0\x01\n\x0b\x41udioFormat\x12\x1c\n\x18\x41UDIO_FORMAT_UNSPECIFIED\x10\x00\x12\x14\n\x10\x41UDIO_FORMAT_MP3\x10\x01\x12\x14\n\x10\x41UDIO_FORMAT_OGG\x10\x02\x12\x14\n\x10\x41UDIO_FORMAT_WAV\x10\x03\x12\x14\n\x10\x41UDIO_FORMAT_AAC\x10\x04\x12\x1b\n\x17\x41UDIO_FORMAT_OGG_IN_UDF\x10\x05\x42I\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x03Hubb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.audio_format_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\003Hub'
  _globals['_AUDIOFORMAT']._serialized_start=152
  _globals['_AUDIOFORMAT']._serialized_end=312
# @@protoc_insertion_point(module_scope)
