# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_malfunctions_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_malfunctions_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_malfunctions_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_device_dot_common_dot_device__malfunctions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n^systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_malfunctions_part.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\x1aYsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_malfunctions.proto\"\x8a\x01\n\x16\x44\x65viceMalfunctionsPart\x12p\n\x13\x64\x65vice_malfunctions\x18\x01 \x01(\x0b\x32S.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceMalfunctionsBF\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.device_malfunctions_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_DEVICEMALFUNCTIONSPART']._serialized_start=255
  _globals['_DEVICEMALFUNCTIONSPART']._serialized_end=393
# @@protoc_insertion_point(module_scope)
