# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_event_settings.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_event_settings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels import patch_type_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_patch__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n[systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_event_settings.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\x1a\x42systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/patch_type.proto\"\xe6\x06\n\x17\x43ommonEventSettingsPart\x12\x85\x01\n\x16\x65nabled_event_settings\x18\x01 \x03(\x0e\x32\x65.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.CommonEventSettingsPart.EventSetting\x12\x8a\x01\n\x1b\x65vent_settings_capabilities\x18\x02 \x03(\x0e\x32\x65.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.CommonEventSettingsPart.EventSetting\x1a\xa1\x01\n\x19\x45ventSettingsPartSettings\x12\x83\x01\n\x0e\x65vent_settings\x18\x01 \x03(\x0b\x32k.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.CommonEventSettingsPart.EventSettingsPatch\x1a\xe5\x01\n\x12\x45ventSettingsPatch\x12}\n\x0e\x65vent_settings\x18\x01 \x01(\x0e\x32\x65.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.CommonEventSettingsPart.EventSetting\x12P\n\npatch_type\x18\x02 \x01(\x0e\x32<.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.PatchType\"\xa9\x01\n\x0c\x45ventSetting\x12\x1d\n\x19\x45VENT_SETTING_UNSPECIFIED\x10\x00\x12\'\n#EVENT_SETTING_EVENT_BY_USER_ENABLED\x10\x01\x12+\n\'EVENT_SETTING_EVENT_BY_SCENARIO_ENABLED\x10\x02\x12$\n EVENT_SETTING_EVENT_BY_DOOR_OPEN\x10\x03\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.device_event_settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_COMMONEVENTSETTINGSPART']._serialized_start=296
  _globals['_COMMONEVENTSETTINGSPART']._serialized_end=1166
  _globals['_COMMONEVENTSETTINGSPART_EVENTSETTINGSPARTSETTINGS']._serialized_start=601
  _globals['_COMMONEVENTSETTINGSPART_EVENTSETTINGSPARTSETTINGS']._serialized_end=762
  _globals['_COMMONEVENTSETTINGSPART_EVENTSETTINGSPATCH']._serialized_start=765
  _globals['_COMMONEVENTSETTINGSPART_EVENTSETTINGSPATCH']._serialized_end=994
  _globals['_COMMONEVENTSETTINGSPART_EVENTSETTING']._serialized_start=997
  _globals['_COMMONEVENTSETTINGSPART_EVENTSETTING']._serialized_end=1166
# @@protoc_insertion_point(module_scope)
