# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_fire_zone_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_fire_zone_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n[systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_fire_zone_part.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\"\xe6\x02\n\x12\x44\x65viceFireZonePart\x12\x1b\n\x13\x64\x65vice_fire_zone_id\x18\x01 \x01(\t\x12t\n\x0c\x63\x61pabilities\x18\x02 \x03(\x0e\x32^.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceFireZonePart.Capability\x1aV\n\x1a\x44\x65viceFireZonePartSettings\x12 \n\x13\x64\x65vice_fire_zone_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x16\n\x14_device_fire_zone_id\"e\n\nCapability\x12\x1a\n\x16\x43\x41PABILITY_UNSPECIFIED\x10\x00\x12\x18\n\x14\x43\x41PABILITY_FIRE_ZONE\x10\x01\x12!\n\x1d\x43\x41PABILITY_DESELECT_FIRE_ZONE\x10\x02\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.device_fire_zone_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_DEVICEFIREZONEPART']._serialized_start=228
  _globals['_DEVICEFIREZONEPART']._serialized_end=586
  _globals['_DEVICEFIREZONEPART_DEVICEFIREZONEPARTSETTINGS']._serialized_start=397
  _globals['_DEVICEFIREZONEPART_DEVICEFIREZONEPARTSETTINGS']._serialized_end=483
  _globals['_DEVICEFIREZONEPART_CAPABILITY']._serialized_start=485
  _globals['_DEVICEFIREZONEPART_CAPABILITY']._serialized_end=586
# @@protoc_insertion_point(module_scope)
