# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_telemetry_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_telemetry_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_telemetry_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_device_dot_common_dot_device__telemetry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n[systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_telemetry_part.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\x1aVsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_telemetry.proto\"\xf2\x04\n\x13\x44\x65viceTelemetryPart\x12j\n\x10\x64\x65vice_telemetry\x18\x01 \x01(\x0b\x32P.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceTelemetry\x12u\n\x0c\x63\x61pabilities\x18\x02 \x03(\x0e\x32_.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceTelemetryPart.Capability\x12|\n\x0f\x63onnection_type\x18\x03 \x01(\x0e\x32\x63.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceTelemetryPart.ConnectionType\"r\n\nCapability\x12\x1a\n\x16\x43\x41PABILITY_UNSPECIFIED\x10\x00\x12&\n\"CAPABILITY_DEVICE_SIGNAL_SUPPORTED\x10\x01\x12 \n\x1c\x43\x41PABILITY_CONNECTION_STATUS\x10\x02\"\x85\x01\n\x0e\x43onnectionType\x12\x1f\n\x1b\x43ONNECTION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x43ONNECTION_TYPE_JEWELLER\x10\x01\x12\x19\n\x15\x43ONNECTION_TYPE_FIBRA\x10\x02\x12\x19\n\x15\x43ONNECTION_TYPE_OTHER\x10\x03\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.device_telemetry_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_DEVICETELEMETRYPART']._serialized_start=249
  _globals['_DEVICETELEMETRYPART']._serialized_end=875
  _globals['_DEVICETELEMETRYPART_CAPABILITY']._serialized_start=625
  _globals['_DEVICETELEMETRYPART_CAPABILITY']._serialized_end=739
  _globals['_DEVICETELEMETRYPART_CONNECTIONTYPE']._serialized_start=742
  _globals['_DEVICETELEMETRYPART_CONNECTIONTYPE']._serialized_end=875
# @@protoc_insertion_point(module_scope)
