# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_tamper_status_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_tamper_status_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_tamper_status_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_device_dot_common_dot_device__tamper__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n_systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_tamper_status_part.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\x1aZsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_tamper_status.proto\"\xd4\x02\n\x16\x44\x65viceTamperStatusPart\x12q\n\x14\x64\x65vice_tamper_status\x18\x01 \x01(\x0e\x32S.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceTamperStatus\x12x\n\x0c\x63\x61pabilities\x18\x02 \x03(\x0e\x32\x62.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceTamperStatusPart.Capability\"M\n\nCapability\x12\x1a\n\x16\x43\x41PABILITY_UNSPECIFIED\x10\x00\x12#\n\x1f\x43\x41PABILITY_DEVICE_TAMPER_STATUS\x10\x01\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.device_tamper_status_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_DEVICETAMPERSTATUSPART']._serialized_start=257
  _globals['_DEVICETAMPERSTATUSPART']._serialized_end=597
  _globals['_DEVICETAMPERSTATUSPART_CAPABILITY']._serialized_start=520
  _globals['_DEVICETAMPERSTATUSPART_CAPABILITY']._serialized_end=597
# @@protoc_insertion_point(module_scope)
