# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/door_open_too_long_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/door_open_too_long_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n]systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/door_open_too_long_part.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\x1a\x1egoogle/protobuf/duration.proto\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\"\xfc\x02\n DoorOpenTooLongEventSettingsPart\x12*\n\x07seconds\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x82\x01\n\x0c\x63\x61pabilities\x18\x02 \x03(\x0e\x32l.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DoorOpenTooLongEventSettingsPart.Capability\x1aZ\n\x1b\x44oorOpenTooLongPartSettings\x12/\n\x07seconds\x18\x01 \x01(\x0b\x32\x19.google.protobuf.DurationH\x00\x88\x01\x01\x42\n\n\x08_seconds\"K\n\nCapability\x12\x1a\n\x16\x43\x41PABILITY_UNSPECIFIED\x10\x00\x12!\n\x1d\x43\x41PABILITY_DOOR_OPEN_TOO_LONG\x10\x01\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.door_open_too_long_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_DOOROPENTOOLONGEVENTSETTINGSPART']._serialized_start=262
  _globals['_DOOROPENTOOLONGEVENTSETTINGSPART']._serialized_end=642
  _globals['_DOOROPENTOOLONGEVENTSETTINGSPART_DOOROPENTOOLONGPARTSETTINGS']._serialized_start=475
  _globals['_DOOROPENTOOLONGEVENTSETTINGSPART_DOOROPENTOOLONGPARTSETTINGS']._serialized_end=565
  _globals['_DOOROPENTOOLONGEVENTSETTINGSPART_CAPABILITY']._serialized_start=567
  _globals['_DOOROPENTOOLONGEVENTSETTINGSPART_CAPABILITY']._serialized_end=642
# @@protoc_insertion_point(module_scope)
