# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/ethernet_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/ethernet_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nSsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/ethernet_part.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\"\x92\x04\n\x0c\x45thernetPart\x12u\n\x0f\x65thernet_status\x18\x01 \x01(\x0e\x32\\.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.EthernetPart.EthernetStatus\x12\x1b\n\x13is_ethernet_enabled\x18\x02 \x01(\x08\x12\x17\n\x0fis_dhcp_enabled\x18\x03 \x01(\x08\x12\x13\n\x0bmac_address\x18\x04 \x01(\t\x12\n\n\x02ip\x18\x05 \x01(\t\x12\x0c\n\x04mask\x18\x06 \x01(\t\x12\x0c\n\x04gate\x18\x07 \x01(\t\x12n\n\x0c\x63\x61pabilities\x18\x08 \x03(\x0e\x32X.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.EthernetPart.Capability\"e\n\x0e\x45thernetStatus\x12\x1f\n\x1b\x45THERNET_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x45THERNET_STATUS_NOT_OK\x10\x01\x12\x16\n\x12\x45THERNET_STATUS_OK\x10\x02\"A\n\nCapability\x12\x1a\n\x16\x43\x41PABILITY_UNSPECIFIED\x10\x00\x12\x17\n\x13\x43\x41PABILITY_ETHERNET\x10\x01\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.ethernet_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_ETHERNETPART']._serialized_start=220
  _globals['_ETHERNETPART']._serialized_end=750
  _globals['_ETHERNETPART_ETHERNETSTATUS']._serialized_start=582
  _globals['_ETHERNETPART_ETHERNETSTATUS']._serialized_end=683
  _globals['_ETHERNETPART_CAPABILITY']._serialized_start=685
  _globals['_ETHERNETPART_CAPABILITY']._serialized_end=750
# @@protoc_insertion_point(module_scope)
