# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/external_antennas_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/external_antennas_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\\systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/external_antennas_part.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\"\x90\x05\n\x14\x45xternalAntennasPart\x12\x80\x01\n\x11\x65xternal_antennas\x18\x01 \x03(\x0b\x32\x65.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.ExternalAntennasPart.ExternalAntenna\x1a\x87\x02\n\x0f\x45xternalAntenna\x12w\n\x0c\x61ntenna_type\x18\x01 \x01(\x0e\x32\x61.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.ExternalAntennasPart.AntennaType\x12{\n\x0e\x61ntenna_status\x18\x02 \x01(\x0e\x32\x63.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.ExternalAntennasPart.AntennaStatus\"^\n\x0b\x41ntennaType\x12\x1c\n\x18\x41NTENNA_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15\x41NTENNA_TYPE_JEWELLER\x10\x01\x12\x16\n\x12\x41NTENNA_TYPE_WINGS\x10\x02\"\x8a\x01\n\rAntennaStatus\x12\x1e\n\x1a\x41NTENNA_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x41NTENNA_STATUS_CONNECTED\x10\x01\x12\x1f\n\x1b\x41NTENNA_STATUS_DISCONNECTED\x10\x02\x12\x1a\n\x16\x41NTENNA_STATUS_DAMAGED\x10\x03\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.external_antennas_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_EXTERNALANTENNASPART']._serialized_start=162
  _globals['_EXTERNALANTENNASPART']._serialized_end=818
  _globals['_EXTERNALANTENNASPART_EXTERNALANTENNA']._serialized_start=318
  _globals['_EXTERNALANTENNASPART_EXTERNALANTENNA']._serialized_end=581
  _globals['_EXTERNALANTENNASPART_ANTENNATYPE']._serialized_start=583
  _globals['_EXTERNALANTENNASPART_ANTENNATYPE']._serialized_end=677
  _globals['_EXTERNALANTENNASPART_ANTENNASTATUS']._serialized_start=680
  _globals['_EXTERNALANTENNASPART_ANTENNASTATUS']._serialized_end=818
# @@protoc_insertion_point(module_scope)
