# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/hopping_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/hopping_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nRsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/hopping_part.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\"\xe8\x03\n\x0bHoppingPart\x12x\n\x11\x66requency_hopping\x18\x01 \x01(\x0e\x32].systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.HoppingPart.FrequencyHopping\x12m\n\x0c\x63\x61pabilities\x18\x02 \x03(\x0e\x32W.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.HoppingPart.Capability\"s\n\x10\x46requencyHopping\x12!\n\x1d\x46REQUENCY_HOPPING_UNSPECIFIED\x10\x00\x12\x1e\n\x1a\x46REQUENCY_HOPPING_INACTIVE\x10\x01\x12\x1c\n\x18\x46REQUENCY_HOPPING_ACTIVE\x10\x02\"{\n\nCapability\x12\x1a\n\x16\x43\x41PABILITY_UNSPECIFIED\x10\x00\x12 \n\x1c\x43\x41PABILITY_HOPPING_SUPPORTED\x10\x01\x12/\n+CAPABILITY_HOPPING_EU_TECHNOLOGY_REX_BRIDGE\x10\x02\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.hopping_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_HOPPINGPART']._serialized_start=152
  _globals['_HOPPINGPART']._serialized_end=640
  _globals['_HOPPINGPART_FREQUENCYHOPPING']._serialized_start=400
  _globals['_HOPPINGPART_FREQUENCYHOPPING']._serialized_end=515
  _globals['_HOPPINGPART_CAPABILITY']._serialized_start=517
  _globals['_HOPPINGPART_CAPABILITY']._serialized_end=640
# @@protoc_insertion_point(module_scope)
