# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/language.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/language.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nNsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/language.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto*\xaa\x05\n\x08Language\x12\x18\n\x14LANGUAGE_UNSPECIFIED\x10\x00\x12\x13\n\x0fLANGUAGE_ARABIC\x10\x01\x12\x14\n\x10LANGUAGE_ENGLISH\x10\x02\x12\x13\n\x0fLANGUAGE_FRENCH\x10\x03\x12\x14\n\x10LANGUAGE_SPANISH\x10\x04\x12\x13\n\x0fLANGUAGE_DANISH\x10\x05\x12\x16\n\x12LANGUAGE_NORWEGIAN\x10\x06\x12\x14\n\x10LANGUAGE_SWEDISH\x10\x07\x12\x14\n\x10LANGUAGE_FINNISH\x10\x08\x12\x14\n\x10LANGUAGE_RUSSIAN\x10\t\x12\x14\n\x10LANGUAGE_CHINESE\x10\n\x12\x12\n\x0eLANGUAGE_DUTCH\x10\x0b\x12\x13\n\x0fLANGUAGE_GERMAN\x10\x0c\x12\x12\n\x0eLANGUAGE_GREEK\x10\r\x12\x14\n\x10LANGUAGE_ITALIAN\x10\x0e\x12\x13\n\x0fLANGUAGE_POLISH\x10\x0f\x12\x17\n\x13LANGUAGE_PORTUGUESE\x10\x10\x12\x14\n\x10LANGUAGE_TURKISH\x10\x11\x12\x12\n\x0eLANGUAGE_CZECH\x10\x12\x12\x13\n\x0fLANGUAGE_SLOVAK\x10\x13\x12\x16\n\x12LANGUAGE_BULGARIAN\x10\x14\x12\x16\n\x12LANGUAGE_HUNGARIAN\x10\x15\x12\x15\n\x11LANGUAGE_ROMANIAN\x10\x16\x12\x18\n\x14LANGUAGE_BELORUSSIAN\x10\x17\x12\x16\n\x12LANGUAGE_UKRAINIAN\x10\x18\x12\x15\n\x11LANGUAGE_ESTONIAN\x10\x19\x12\x17\n\x13LANGUAGE_LITHUANIAN\x10\x1a\x12\x14\n\x10LANGUAGE_LATVIAN\x10\x1b\x12\x13\n\x0fLANGUAGE_KOREAN\x10\x1c\x12\x15\n\x11LANGUAGE_JAPANESE\x10\x1d\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.language_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_LANGUAGE']._serialized_start=215
  _globals['_LANGUAGE']._serialized_end=897
# @@protoc_insertion_point(module_scope)
