# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/language_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/language_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import language_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_device_dot_common_dot_language__pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nSsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/language_part.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\x1aNsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/language.proto\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\"\xdb\x02\n\x0cLanguagePart\x12[\n\x08language\x18\x01 \x01(\x0e\x32I.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.Language\x12\x66\n\x13\x61vailable_languages\x18\x02 \x03(\x0e\x32I.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.Language\x1a\x85\x01\n\x14LanguagePartSettings\x12`\n\x08language\x18\x01 \x01(\x0e\x32I.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.LanguageH\x00\x88\x01\x01\x42\x0b\n\t_languageBF\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.language_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_LANGUAGEPART']._serialized_start=300
  _globals['_LANGUAGEPART']._serialized_end=647
  _globals['_LANGUAGEPART_LANGUAGEPARTSETTINGS']._serialized_start=514
  _globals['_LANGUAGEPART_LANGUAGEPARTSETTINGS']._serialized_end=647
# @@protoc_insertion_point(module_scope)
