# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/takeover_module_compatibility_mode.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/takeover_module_compatibility_mode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nhsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/takeover_module_compatibility_mode.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto*\xab\x02\n\x1fTakeoverModuleCompatibilityMode\x12\x32\n.TAKEOVER_MODULE_COMPATIBILITY_MODE_UNSPECIFIED\x10\x00\x12=\n9TAKEOVER_MODULE_COMPATIBILITY_MODE_HONEYWELL_RESIDEO_2GIG\x10\x01\x12\x38\n4TAKEOVER_MODULE_COMPATIBILITY_MODE_QOLSYS_INTERLOGIX\x10\x02\x12*\n&TAKEOVER_MODULE_COMPATIBILITY_MODE_DSC\x10\x03\x12/\n+TAKEOVER_MODULE_COMPATIBILITY_MODE_AT_AND_T\x10\x04\x42L\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x06\x43ommonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.takeover_module_compatibility_mode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\006Common'
  _globals['_TAKEOVERMODULECOMPATIBILITYMODE']._serialized_start=241
  _globals['_TAKEOVERMODULECOMPATIBILITYMODE']._serialized_end=540
# @@protoc_insertion_point(module_scope)
