# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/third_party_device_offline_timeout_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/third_party_device_offline_timeout_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nmsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/third_party_device_offline_timeout_part.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\"\xe9\x05\n\"ThirdPartyDeviceOfflineTimeoutPart\x12\x8b\x01\n\x0foffline_timeout\x18\x01 \x01(\x0e\x32r.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.ThirdPartyDeviceOfflineTimeoutPart.OfflineTimeout\x12\x96\x01\n\x1a\x61vailable_offline_timeouts\x18\x02 \x03(\x0e\x32r.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.ThirdPartyDeviceOfflineTimeoutPart.OfflineTimeout\x1a\xd3\x01\n*ThirdPartyDeviceOfflineTimeoutPartSettings\x12\x90\x01\n\x0foffline_timeout\x18\x01 \x01(\x0e\x32r.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.ThirdPartyDeviceOfflineTimeoutPart.OfflineTimeoutH\x00\x88\x01\x01\x42\x12\n\x10_offline_timeout\"\xc5\x01\n\x0eOfflineTimeout\x12\x1f\n\x1bOFFLINE_TIMEOUT_UNSPECIFIED\x10\x00\x12\x1b\n\x17OFFLINE_TIMEOUT_4_HOURS\x10\x01\x12\x1b\n\x17OFFLINE_TIMEOUT_8_HOURS\x10\x02\x12\x1c\n\x18OFFLINE_TIMEOUT_12_HOURS\x10\x03\x12\x1c\n\x18OFFLINE_TIMEOUT_18_HOURS\x10\x04\x12\x1c\n\x18OFFLINE_TIMEOUT_24_HOURS\x10\x05\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.third_party_device_offline_timeout_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_THIRDPARTYDEVICEOFFLINETIMEOUTPART']._serialized_start=246
  _globals['_THIRDPARTYDEVICEOFFLINETIMEOUTPART']._serialized_end=991
  _globals['_THIRDPARTYDEVICEOFFLINETIMEOUTPART_THIRDPARTYDEVICEOFFLINETIMEOUTPARTSETTINGS']._serialized_start=580
  _globals['_THIRDPARTYDEVICEOFFLINETIMEOUTPART_THIRDPARTYDEVICEOFFLINETIMEOUTPARTSETTINGS']._serialized_end=791
  _globals['_THIRDPARTYDEVICEOFFLINETIMEOUTPART_OFFLINETIMEOUT']._serialized_start=794
  _globals['_THIRDPARTYDEVICEOFFLINETIMEOUTPART_OFFLINETIMEOUT']._serialized_end=991
# @@protoc_insertion_point(module_scope)
