# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/commonmodels/device/accessdevice/access_card_type_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/commonmodels/device/accessdevice/access_card_type_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_color_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_device_dot_common_dot_device__color__pb2
from systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice import access_card_type_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_commonmodels_dot_device_dot_accessdevice_dot_access__card__type__pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nZsystems/ajax/api/ecosystem/v2/commonmodels/device/accessdevice/access_card_type_part.proto\x12>systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice\x1aRsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_color.proto\x1aUsystems/ajax/api/ecosystem/v2/commonmodels/device/accessdevice/access_card_type.proto\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\"\xcb\x03\n\x12\x41\x63\x63\x65ssCardTypePart\x12\x62\n\x0c\x64\x65vice_color\x18\x01 \x01(\x0e\x32L.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceColor\x12h\n\x10\x61\x63\x63\x65ss_card_type\x18\x02 \x01(\x0e\x32N.systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice.AccessCardType\x1a\xe6\x01\n\x16\x41\x63\x63\x65ssCardTypeSettings\x12\x62\n\x0c\x64\x65vice_color\x18\x01 \x01(\x0e\x32L.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceColor\x12h\n\x10\x61\x63\x63\x65ss_card_type\x18\x02 \x01(\x0e\x32N.systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice.AccessCardTypeBE\n>systems.ajax.api.ecosystem.v2.commonmodels.device.accessdeviceP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice.access_card_type_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n>systems.ajax.api.ecosystem.v2.commonmodels.device.accessdeviceP\001\272\002\000'
  _globals['_ACCESSCARDTYPEPART']._serialized_start=397
  _globals['_ACCESSCARDTYPEPART']._serialized_end=856
  _globals['_ACCESSCARDTYPEPART_ACCESSCARDTYPESETTINGS']._serialized_start=626
  _globals['_ACCESSCARDTYPEPART_ACCESSCARDTYPESETTINGS']._serialized_end=856
# @@protoc_insertion_point(module_scope)
