# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/commonmodels/device/accessdevice/access_device_state_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/commonmodels/device/accessdevice/access_device_state_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n]systems/ajax/api/ecosystem/v2/commonmodels/device/accessdevice/access_device_state_part.proto\x12>systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\"\xc0\x03\n\x15\x41\x63\x63\x65ssDeviceStatePart\x12\x84\x01\n\x13\x61\x63\x63\x65ss_device_state\x18\x01 \x01(\x0e\x32g.systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice.AccessDeviceStatePart.AccessDeviceState\x1a\xa2\x01\n\x19\x41\x63\x63\x65ssDeviceStateSettings\x12\x84\x01\n\x13\x61\x63\x63\x65ss_device_state\x18\x01 \x01(\x0e\x32g.systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice.AccessDeviceStatePart.AccessDeviceState\"{\n\x11\x41\x63\x63\x65ssDeviceState\x12#\n\x1f\x41\x43\x43\x45SS_DEVICE_STATE_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x41\x43\x43\x45SS_DEVICE_STATE_ENABLED\x10\x01\x12 \n\x1c\x41\x43\x43\x45SS_DEVICE_STATE_DISABLED\x10\x02\x42\x45\n>systems.ajax.api.ecosystem.v2.commonmodels.device.accessdeviceP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice.access_device_state_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n>systems.ajax.api.ecosystem.v2.commonmodels.device.accessdeviceP\001\272\002\000'
  _globals['_ACCESSDEVICESTATEPART']._serialized_start=229
  _globals['_ACCESSDEVICESTATEPART']._serialized_end=677
  _globals['_ACCESSDEVICESTATEPART_ACCESSDEVICESTATESETTINGS']._serialized_start=390
  _globals['_ACCESSDEVICESTATEPART_ACCESSDEVICESTATESETTINGS']._serialized_end=552
  _globals['_ACCESSDEVICESTATEPART_ACCESSDEVICESTATE']._serialized_start=554
  _globals['_ACCESSDEVICESTATEPART_ACCESSDEVICESTATE']._serialized_end=677
# @@protoc_insertion_point(module_scope)
