# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/commonmodels/device/accessdevice/access_card_profile_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/commonmodels/device/accessdevice/access_card_profile_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n]systems/ajax/api/ecosystem/v2/commonmodels/device/accessdevice/access_card_profile_part.proto\x12>systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\"\\\n\x15\x41\x63\x63\x65ssCardProfilePart\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x1a)\n\x19\x41\x63\x63\x65ssCardProfileSettings\x12\x0c\n\x04name\x18\x01 \x01(\tBE\n>systems.ajax.api.ecosystem.v2.commonmodels.device.accessdeviceP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice.access_card_profile_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n>systems.ajax.api.ecosystem.v2.commonmodels.device.accessdeviceP\001\272\002\000'
  _globals['_ACCESSCARDPROFILEPART']._serialized_start=228
  _globals['_ACCESSCARDPROFILEPART']._serialized_end=320
  _globals['_ACCESSCARDPROFILEPART_ACCESSCARDPROFILESETTINGS']._serialized_start=279
  _globals['_ACCESSCARDPROFILEPART_ACCESSCARDPROFILESETTINGS']._serialized_end=320
# @@protoc_insertion_point(module_scope)
