# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/commonmodels/device/accessdevice/access_device_security_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/commonmodels/device/accessdevice/access_device_security_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n`systems/ajax/api/ecosystem/v2/commonmodels/device/accessdevice/access_device_security_part.proto\x12>systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\"\xa0\x08\n\x18\x41\x63\x63\x65ssDeviceSecurityPart\x12\x15\n\rperimeter_arm\x18\x01 \x01(\x08\x12\x84\x01\n\x11group_permissions\x18\x02 \x03(\x0b\x32i.systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice.AccessDeviceSecurityPart.GroupPermissions\x12\xa4\x01\n#access_device_security_capabilities\x18\x03 \x03(\x0e\x32w.systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice.AccessDeviceSecurityPart.AccessDeviceSecurityCapability\x1a\xb6\x01\n\x10GroupPermissions\x12\x10\n\x08group_id\x18\x01 \x01(\t\x12\x8f\x01\n\x17group_permissions_state\x18\x02 \x01(\x0e\x32n.systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice.AccessDeviceSecurityPart.GroupPermissionsState\x1a\xbc\x01\n\x1c\x41\x63\x63\x65ssDeviceSecuritySettings\x12\x15\n\rperimeter_arm\x18\x01 \x01(\x08\x12\x84\x01\n\x11group_permissions\x18\x02 \x03(\x0b\x32i.systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice.AccessDeviceSecurityPart.GroupPermissions\"\x8b\x01\n\x15GroupPermissionsState\x12\'\n#GROUP_PERMISSIONS_STATE_UNSPECIFIED\x10\x00\x12#\n\x1fGROUP_PERMISSIONS_STATE_ENABLED\x10\x01\x12$\n GROUP_PERMISSIONS_STATE_DISABLED\x10\x02\"\xb8\x01\n\x1e\x41\x63\x63\x65ssDeviceSecurityCapability\x12\x31\n-ACCESS_DEVICE_SECURITY_CAPABILITY_UNSPECIFIED\x10\x00\x12.\n*ACCESS_DEVICE_SECURITY_CAPABILITY_SETTINGS\x10\x01\x12\x33\n/ACCESS_DEVICE_SECURITY_CAPABILITY_PERIMETER_ARM\x10\x02\x42\x45\n>systems.ajax.api.ecosystem.v2.commonmodels.device.accessdeviceP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.commonmodels.device.accessdevice.access_device_security_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n>systems.ajax.api.ecosystem.v2.commonmodels.device.accessdeviceP\001\272\002\000'
  _globals['_ACCESSDEVICESECURITYPART']._serialized_start=232
  _globals['_ACCESSDEVICESECURITYPART']._serialized_end=1288
  _globals['_ACCESSDEVICESECURITYPART_GROUPPERMISSIONS']._serialized_start=586
  _globals['_ACCESSDEVICESECURITYPART_GROUPPERMISSIONS']._serialized_end=768
  _globals['_ACCESSDEVICESECURITYPART_ACCESSDEVICESECURITYSETTINGS']._serialized_start=771
  _globals['_ACCESSDEVICESECURITYPART_ACCESSDEVICESECURITYSETTINGS']._serialized_end=959
  _globals['_ACCESSDEVICESECURITYPART_GROUPPERMISSIONSSTATE']._serialized_start=962
  _globals['_ACCESSDEVICESECURITYPART_GROUPPERMISSIONSSTATE']._serialized_end=1101
  _globals['_ACCESSDEVICESECURITYPART_ACCESSDEVICESECURITYCAPABILITY']._serialized_start=1104
  _globals['_ACCESSDEVICESECURITYPART_ACCESSDEVICESECURITYCAPABILITY']._serialized_end=1288
# @@protoc_insertion_point(module_scope)
