syntax = "proto3";

package systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common;

import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto";

option java_multiple_files = true;
option java_package = "systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common";
option swift_prefix = "";

message AlwaysActivePart {
  bool always_active = 1;
  repeated .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.AlwaysActivePart.Capability capabilities = 2;

  message AlwaysActivePartSettings {
    optional bool always_active = 1;
  }

  enum Capability {
    CAPABILITY_UNSPECIFIED = 0;
    CAPABILITY_ALWAYS_ACTIVE_SUPPORTED = 1;
  }
}
