syntax = "proto3";

package systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common;

import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto";

option java_multiple_files = true;
option java_package = "systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common";
option swift_prefix = "";

message DeviceLocationPart {
  string device_location = 1;
  repeated .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceLocationPart.Capability capabilities = 2;

  message DeviceLocationPartSettings {
    optional string device_location = 1;
  }

  enum Capability {
    CAPABILITY_UNSPECIFIED = 0;
    CAPABILITY_DEVICE_LOCATION = 1;
  }
}
