syntax = "proto3";

package systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common;

import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto";
import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_transmission_power_mode.proto";

option java_multiple_files = true;
option java_package = "systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common";
option swift_prefix = "";

message DeviceTransmissionPowerModePart {
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceTransmissionPowerMode device_transmission_power_mode = 1;

  message DeviceTransmissionPowerModePartSettings {
    optional .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceTransmissionPowerMode device_transmission_power_mode = 2;
  }
}
