syntax = "proto3";

package systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common;

import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_tamper_status.proto";

option java_multiple_files = true;
option java_package = "systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common";
option swift_prefix = "";

message DeviceTamperStatusPart {
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceTamperStatus device_tamper_status = 1;
  repeated .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceTamperStatusPart.Capability capabilities = 2;

  enum Capability {
    CAPABILITY_UNSPECIFIED = 0;
    CAPABILITY_DEVICE_TAMPER_STATUS = 1;
  }
}
