syntax = "proto3";

package systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common;

import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto";

option java_multiple_files = true;
option java_package = "systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common";
option swift_prefix = "";

message DeviceFireZonePart {
  string device_fire_zone_id = 1;
  repeated .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceFireZonePart.Capability capabilities = 2;

  message DeviceFireZonePartSettings {
    optional string device_fire_zone_id = 1;
  }

  enum Capability {
    CAPABILITY_UNSPECIFIED = 0;
    CAPABILITY_FIRE_ZONE = 1;
    CAPABILITY_DESELECT_FIRE_ZONE = 2;
  }
}
