syntax = "proto3";

package systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common;

import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto";

option java_multiple_files = true;
option java_package = "systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common";
option swift_prefix = "";

enum Language {
  LANGUAGE_UNSPECIFIED = 0;
  LANGUAGE_ARABIC = 1;
  LANGUAGE_ENGLISH = 2;
  LANGUAGE_FRENCH = 3;
  LANGUAGE_SPANISH = 4;
  LANGUAGE_DANISH = 5;
  LANGUAGE_NORWEGIAN = 6;
  LANGUAGE_SWEDISH = 7;
  LANGUAGE_FINNISH = 8;
  LANGUAGE_RUSSIAN = 9;
  LANGUAGE_CHINESE = 10;
  LANGUAGE_DUTCH = 11;
  LANGUAGE_GERMAN = 12;
  LANGUAGE_GREEK = 13;
  LANGUAGE_ITALIAN = 14;
  LANGUAGE_POLISH = 15;
  LANGUAGE_PORTUGUESE = 16;
  LANGUAGE_TURKISH = 17;
  LANGUAGE_CZECH = 18;
  LANGUAGE_SLOVAK = 19;
  LANGUAGE_BULGARIAN = 20;
  LANGUAGE_HUNGARIAN = 21;
  LANGUAGE_ROMANIAN = 22;
  LANGUAGE_BELORUSSIAN = 23;
  LANGUAGE_UKRAINIAN = 24;
  LANGUAGE_ESTONIAN = 25;
  LANGUAGE_LITHUANIAN = 26;
  LANGUAGE_LATVIAN = 27;
  LANGUAGE_KOREAN = 28;
  LANGUAGE_JAPANESE = 29;
}
