# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/z_wave_device/z_wave_device_clusters_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/z_wave_device/z_wave_device_clusters_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nhsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/z_wave_device/z_wave_device_clusters_part.proto\x12\x46systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.z_wave_device\"\x89\x05\n\x17ZWaveDeviceClustersPart\x12y\n\x08\x63lusters\x18\x01 \x03(\x0b\x32g.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.z_wave_device.ZWaveDeviceClustersPart.Cluster\x1a\xf2\x03\n\x07\x43luster\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12~\n\x05\x62\x61sic\x18\x03 \x01(\x0b\x32m.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.z_wave_device.ZWaveDeviceClustersPart.Cluster.BasicH\x00\x12\x7f\n\x06on_off\x18\x04 \x01(\x0b\x32m.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.z_wave_device.ZWaveDeviceClustersPart.Cluster.OnOffH\x00\x12\x9f\x01\n\x16\x65lectrical_measurement\x18\x05 \x01(\x0b\x32}.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.z_wave_device.ZWaveDeviceClustersPart.Cluster.ElectricalMeasurementH\x00\x1a\x07\n\x05\x42\x61sic\x1a\x07\n\x05OnOff\x1a\x17\n\x15\x45lectricalMeasurementB\x06\n\x04kindBM\nFsystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.z_wave_deviceP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.z_wave_device.z_wave_device_clusters_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nFsystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.z_wave_deviceP\001\272\002\000'
  _globals['_ZWAVEDEVICECLUSTERSPART']._serialized_start=181
  _globals['_ZWAVEDEVICECLUSTERSPART']._serialized_end=830
  _globals['_ZWAVEDEVICECLUSTERSPART_CLUSTER']._serialized_start=332
  _globals['_ZWAVEDEVICECLUSTERSPART_CLUSTER']._serialized_end=830
  _globals['_ZWAVEDEVICECLUSTERSPART_CLUSTER_BASIC']._serialized_start=781
  _globals['_ZWAVEDEVICECLUSTERSPART_CLUSTER_BASIC']._serialized_end=788
  _globals['_ZWAVEDEVICECLUSTERSPART_CLUSTER_ONOFF']._serialized_start=790
  _globals['_ZWAVEDEVICECLUSTERSPART_CLUSTER_ONOFF']._serialized_end=797
  _globals['_ZWAVEDEVICECLUSTERSPART_CLUSTER_ELECTRICALMEASUREMENT']._serialized_start=799
  _globals['_ZWAVEDEVICECLUSTERSPART_CLUSTER_ELECTRICALMEASUREMENT']._serialized_end=822
# @@protoc_insertion_point(module_scope)
