# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/commonmodels/device/common/associated_member.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/commonmodels/device/common/associated_member.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.logging.proto import formatting_options_pb2 as systems_dot_ajax_dot_logging_dot_proto_dot_formatting__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nPsystems/ajax/api/ecosystem/v2/commonmodels/device/common/associated_member.proto\x12\x38systems.ajax.api.ecosystem.v2.commonmodels.device.common\x1a\x33systems/ajax/logging/proto/formatting_options.proto\"\xcf\x05\n\x10\x41ssociatedMember\x12\x83\x01\n\x17\x61ssociated_space_member\x18\x01 \x01(\x0b\x32`.systems.ajax.api.ecosystem.v2.commonmodels.device.common.AssociatedMember.AssociatedSpaceMemberH\x00\x12v\n\x10\x61ssociated_guest\x18\x02 \x01(\x0b\x32Z.systems.ajax.api.ecosystem.v2.commonmodels.device.common.AssociatedMember.AssociatedGuestH\x00\x12}\n\x14\x64\x65leted_space_member\x18\x03 \x01(\x0b\x32].systems.ajax.api.ecosystem.v2.commonmodels.device.common.AssociatedMember.DeletedSpaceMemberH\x00\x12{\n\x13not_assigned_member\x18\x04 \x01(\x0b\x32\\.systems.ajax.api.ecosystem.v2.commonmodels.device.common.AssociatedMember.NotAssignedMemberH\x00\x1an\n\x15\x41ssociatedSpaceMember\x12\x17\n\x0fspace_member_id\x18\x01 \x01(\t\x12\x19\n\x11space_member_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\nuser_index\x18\x04 \x01(\x05\x1a\x11\n\x0f\x41ssociatedGuest\x1a\x14\n\x12\x44\x65letedSpaceMember\x1a\x13\n\x11NotAssignedMemberB\x13\n\x11\x61ssociated_memberB?\n8systems.ajax.api.ecosystem.v2.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.commonmodels.device.common.associated_member_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n8systems.ajax.api.ecosystem.v2.commonmodels.device.commonP\001\272\002\000'
  _globals['_ASSOCIATEDMEMBER']._serialized_start=196
  _globals['_ASSOCIATEDMEMBER']._serialized_end=915
  _globals['_ASSOCIATEDMEMBER_ASSOCIATEDSPACEMEMBER']._serialized_start=722
  _globals['_ASSOCIATEDMEMBER_ASSOCIATEDSPACEMEMBER']._serialized_end=832
  _globals['_ASSOCIATEDMEMBER_ASSOCIATEDGUEST']._serialized_start=834
  _globals['_ASSOCIATEDMEMBER_ASSOCIATEDGUEST']._serialized_end=851
  _globals['_ASSOCIATEDMEMBER_DELETEDSPACEMEMBER']._serialized_start=853
  _globals['_ASSOCIATEDMEMBER_DELETEDSPACEMEMBER']._serialized_end=873
  _globals['_ASSOCIATEDMEMBER_NOTASSIGNEDMEMBER']._serialized_start=875
  _globals['_ASSOCIATEDMEMBER_NOTASSIGNEDMEMBER']._serialized_end=894
# @@protoc_insertion_point(module_scope)
