# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/commonmodels/device/common/day_alarm_deactivation_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/commonmodels/device/common/day_alarm_deactivation_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nZsystems/ajax/api/ecosystem/v2/commonmodels/device/common/day_alarm_deactivation_part.proto\x12\x38systems.ajax.api.ecosystem.v2.commonmodels.device.common\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\"\xaa\x06\n\x18\x44\x61yAlarmDeactivationPart\x12\x87\x01\n\x16\x64\x61y_alarm_deactivation\x18\x01 \x01(\x0e\x32g.systems.ajax.api.ecosystem.v2.commonmodels.device.common.DayAlarmDeactivationPart.DayAlarmDeactivation\x12\x9e\x01\n#day_alarm_deactivation_capabilities\x18\x02 \x03(\x0e\x32q.systems.ajax.api.ecosystem.v2.commonmodels.device.common.DayAlarmDeactivationPart.DayAlarmDeactivationCapability\x1a\xa8\x01\n\x1c\x44\x61yAlarmDeactivationSettings\x12\x87\x01\n\x16\x64\x61y_alarm_deactivation\x18\x01 \x01(\x0e\x32g.systems.ajax.api.ecosystem.v2.commonmodels.device.common.DayAlarmDeactivationPart.DayAlarmDeactivation\"\x84\x01\n\x1e\x44\x61yAlarmDeactivationCapability\x12\x31\n-DAY_ALARM_DEACTIVATION_CAPABILITY_UNSPECIFIED\x10\x00\x12/\n+DAY_ALARM_DEACTIVATION_CAPABILITY_AVAILABLE\x10\x01\"\xb0\x01\n\x14\x44\x61yAlarmDeactivation\x12&\n\"DAY_ALARM_DEACTIVATION_UNSPECIFIED\x10\x00\x12$\n DAY_ALARM_DEACTIVATION_NO_ACCESS\x10\x01\x12$\n DAY_ALARM_DEACTIVATION_TEMPORARY\x10\x02\x12$\n DAY_ALARM_DEACTIVATION_PERMANENT\x10\x03\x42?\n8systems.ajax.api.ecosystem.v2.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.commonmodels.device.common.day_alarm_deactivation_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n8systems.ajax.api.ecosystem.v2.commonmodels.device.commonP\001\272\002\000'
  _globals['_DAYALARMDEACTIVATIONPART']._serialized_start=220
  _globals['_DAYALARMDEACTIVATIONPART']._serialized_end=1030
  _globals['_DAYALARMDEACTIVATIONPART_DAYALARMDEACTIVATIONSETTINGS']._serialized_start=548
  _globals['_DAYALARMDEACTIVATIONPART_DAYALARMDEACTIVATIONSETTINGS']._serialized_end=716
  _globals['_DAYALARMDEACTIVATIONPART_DAYALARMDEACTIVATIONCAPABILITY']._serialized_start=719
  _globals['_DAYALARMDEACTIVATIONPART_DAYALARMDEACTIVATIONCAPABILITY']._serialized_end=851
  _globals['_DAYALARMDEACTIVATIONPART_DAYALARMDEACTIVATION']._serialized_start=854
  _globals['_DAYALARMDEACTIVATIONPART_DAYALARMDEACTIVATION']._serialized_end=1030
# @@protoc_insertion_point(module_scope)
