# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/commonmodels/device/common/device_index_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/commonmodels/device/common/device_index_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nPsystems/ajax/api/ecosystem/v2/commonmodels/device/common/device_index_part.proto\x12\x38systems.ajax.api.ecosystem.v2.commonmodels.device.common\"\x95\x02\n\x0f\x44\x65viceIndexPart\x12\x14\n\x0c\x64\x65vice_index\x18\x01 \x01(\x05\x12\x82\x01\n\x19\x64\x65vice_index_capabilities\x18\x02 \x03(\x0e\x32_.systems.ajax.api.ecosystem.v2.commonmodels.device.common.DeviceIndexPart.DeviceIndexCapability\"g\n\x15\x44\x65viceIndexCapability\x12\'\n#DEVICE_INDEX_CAPABILITY_UNSPECIFIED\x10\x00\x12%\n!DEVICE_INDEX_CAPABILITY_AVAILABLE\x10\x01\x42?\n8systems.ajax.api.ecosystem.v2.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.commonmodels.device.common.device_index_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n8systems.ajax.api.ecosystem.v2.commonmodels.device.commonP\001\272\002\000'
  _globals['_DEVICEINDEXPART']._serialized_start=143
  _globals['_DEVICEINDEXPART']._serialized_end=420
  _globals['_DEVICEINDEXPART_DEVICEINDEXCAPABILITY']._serialized_start=317
  _globals['_DEVICEINDEXPART_DEVICEINDEXCAPABILITY']._serialized_end=420
# @@protoc_insertion_point(module_scope)
