# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/commonmodels/device/common/fibra_line.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/commonmodels/device/common/fibra_line.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nIsystems/ajax/api/ecosystem/v2/commonmodels/device/common/fibra_line.proto\x12\x38systems.ajax.api.ecosystem.v2.commonmodels.device.common\"\x85\x02\n\tFibraLine\x12X\n\x04line\x18\x01 \x01(\x0b\x32H.systems.ajax.api.ecosystem.v2.commonmodels.device.common.FibraLine.LineH\x00\x12X\n\x04ring\x18\x02 \x01(\x0b\x32H.systems.ajax.api.ecosystem.v2.commonmodels.device.common.FibraLine.RingH\x00\x1a\x15\n\x04Line\x12\r\n\x05value\x18\x01 \x01(\x05\x1a%\n\x04Ring\x12\r\n\x05input\x18\x01 \x01(\x05\x12\x0e\n\x06output\x18\x02 \x01(\x05\x42\x06\n\x04typeB?\n8systems.ajax.api.ecosystem.v2.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.commonmodels.device.common.fibra_line_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n8systems.ajax.api.ecosystem.v2.commonmodels.device.commonP\001\272\002\000'
  _globals['_FIBRALINE']._serialized_start=136
  _globals['_FIBRALINE']._serialized_end=397
  _globals['_FIBRALINE_LINE']._serialized_start=329
  _globals['_FIBRALINE_LINE']._serialized_end=350
  _globals['_FIBRALINE_RING']._serialized_start=352
  _globals['_FIBRALINE_RING']._serialized_end=389
# @@protoc_insertion_point(module_scope)
