# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_event_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_event_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nosystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_event_type.proto\x12Ksystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device*\xfd\x04\n\x19ThirdPartyDeviceEventType\x12-\n)THIRD_PARTY_DEVICE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12+\n\'THIRD_PARTY_DEVICE_EVENT_TYPE_INTRUSION\x10\x01\x12,\n(THIRD_PARTY_DEVICE_EVENT_TYPE_FIRE_ALARM\x10\x02\x12\x31\n-THIRD_PARTY_DEVICE_EVENT_TYPE_AUXILIARY_ALARM\x10\x03\x12.\n*THIRD_PARTY_DEVICE_EVENT_TYPE_PANIC_BUTTON\x10\x04\x12*\n&THIRD_PARTY_DEVICE_EVENT_TYPE_CO_ALARM\x10\x05\x12-\n)THIRD_PARTY_DEVICE_EVENT_TYPE_MALFUNCTION\x10\x06\x12)\n%THIRD_PARTY_DEVICE_EVENT_TYPE_LEAKAGE\x10\x07\x12-\n)THIRD_PARTY_DEVICE_EVENT_TYPE_GLASS_BREAK\x10\x08\x12\x32\n.THIRD_PARTY_DEVICE_EVENT_TYPE_HIGH_TEMPERATURE\x10\t\x12\x31\n-THIRD_PARTY_DEVICE_EVENT_TYPE_LOW_TEMPERATURE\x10\n\x12-\n)THIRD_PARTY_DEVICE_EVENT_TYPE_SMOKE_ALARM\x10\x0b\x12(\n$THIRD_PARTY_DEVICE_EVENT_TYPE_CUSTOM\x10\x0c\x42R\nKsystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_deviceP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device.third_party_device_event_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nKsystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_deviceP\001\272\002\000'
  _globals['_THIRDPARTYDEVICEEVENTTYPE']._serialized_start=193
  _globals['_THIRDPARTYDEVICEEVENTTYPE']._serialized_end=830
# @@protoc_insertion_point(module_scope)
