# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_id_format.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_id_format.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nnsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_id_format.proto\x12Ksystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device*\xb0\x01\n\x18ThirdPartyDeviceIdFormat\x12,\n(THIRD_PARTY_DEVICE_ID_FORMAT_UNSPECIFIED\x10\x00\x12\x34\n0THIRD_PARTY_DEVICE_ID_FORMAT_6_DIGIT_HEXADECIMAL\x10\x01\x12\x30\n,THIRD_PARTY_DEVICE_ID_FORMAT_7_DIGIT_NUMERIC\x10\x02\x42R\nKsystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_deviceP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device.third_party_device_id_format_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nKsystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_deviceP\001\272\002\000'
  _globals['_THIRDPARTYDEVICEIDFORMAT']._serialized_start=192
  _globals['_THIRDPARTYDEVICEIDFORMAT']._serialized_end=368
# @@protoc_insertion_point(module_scope)
