# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_subtype_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_subtype_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device import third_party_device_subtype_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_device_dot_third__party__device_dot_third__party__device__subtype__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nqsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_subtype_part.proto\x12Ksystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\x1alsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_subtype.proto\"\xe9\x04\n\x1bThirdPartyDeviceSubtypePart\x12\x88\x01\n\x1athird_party_device_subtype\x18\x01 \x01(\x0e\x32\x64.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device.ThirdPartyDeviceSubtype\x12\x89\x01\n\x0c\x63\x61pabilities\x18\x64 \x03(\x0e\x32s.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device.ThirdPartyDeviceSubtypePart.Capability\x1a\xd4\x01\n#ThirdPartyDeviceSubtypePartSettings\x12\x8d\x01\n\x1athird_party_device_subtype\x18\x01 \x01(\x0e\x32\x64.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device.ThirdPartyDeviceSubtypeH\x00\x88\x01\x01\x42\x1d\n\x1b_third_party_device_subtype\"\\\n\nCapability\x12\x1a\n\x16\x43\x41PABILITY_UNSPECIFIED\x10\x00\x12\x32\n.CAPABILITY_THIRD_PARTY_DEVICE_SUBTYPE_REQUIRED\x10\x01\x42R\nKsystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_deviceP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device.third_party_device_subtype_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nKsystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_deviceP\001\272\002\000'
  _globals['_THIRDPARTYDEVICESUBTYPEPART']._serialized_start=372
  _globals['_THIRDPARTYDEVICESUBTYPEPART']._serialized_end=989
  _globals['_THIRDPARTYDEVICESUBTYPEPART_THIRDPARTYDEVICESUBTYPEPARTSETTINGS']._serialized_start=683
  _globals['_THIRDPARTYDEVICESUBTYPEPART_THIRDPARTYDEVICESUBTYPEPARTSETTINGS']._serialized_end=895
  _globals['_THIRDPARTYDEVICESUBTYPEPART_CAPABILITY']._serialized_start=897
  _globals['_THIRDPARTYDEVICESUBTYPEPART_CAPABILITY']._serialized_end=989
# @@protoc_insertion_point(module_scope)
