# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_identity_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_identity_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels import third_party_device_type_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_third__party__device__type__pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device import third_party_device_id_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_device_dot_third__party__device_dot_third__party__device__id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nrsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_identity_part.proto\x12Ksystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device\x1aOsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/third_party_device_type.proto\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\x1agsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_id.proto\"\xb1\x04\n\x1cThirdPartyDeviceIdentityPart\x12h\n\x17third_party_device_type\x18\x01 \x01(\x0e\x32G.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.ThirdPartyDeviceType\x12~\n\x15third_party_device_id\x18\x02 \x01(\x0b\x32_.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device.ThirdPartyDeviceId\x12s\n\"available_third_party_device_types\x18\x64 \x03(\x0e\x32G.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.ThirdPartyDeviceType\x1a\xb1\x01\n$ThirdPartyDeviceIdentityPartSettings\x12m\n\x17third_party_device_type\x18\x01 \x01(\x0e\x32G.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.ThirdPartyDeviceTypeH\x00\x88\x01\x01\x42\x1a\n\x18_third_party_device_typeBR\nKsystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_deviceP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device.third_party_device_identity_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nKsystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_deviceP\001\272\002\000'
  _globals['_THIRDPARTYDEVICEIDENTITYPART']._serialized_start=449
  _globals['_THIRDPARTYDEVICEIDENTITYPART']._serialized_end=1010
  _globals['_THIRDPARTYDEVICEIDENTITYPART_THIRDPARTYDEVICEIDENTITYPARTSETTINGS']._serialized_start=833
  _globals['_THIRDPARTYDEVICEIDENTITYPART_THIRDPARTYDEVICEIDENTITYPARTSETTINGS']._serialized_end=1010
# @@protoc_insertion_point(module_scope)
