# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_number_of_buttons_part.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_number_of_buttons_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n{systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/third_party_device/third_party_device_number_of_buttons_part.proto\x12Ksystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\"\xc1\x07\n#ThirdPartyDeviceNumberOfButtonsPart\x12\x9c\x01\n\x11number_of_buttons\x18\x01 \x01(\x0e\x32\x80\x01.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device.ThirdPartyDeviceNumberOfButtonsPart.NumberOfButtons\x12\xa7\x01\n\x1c\x61vailable_numbers_of_buttons\x18\x64 \x03(\x0e\x32\x80\x01.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device.ThirdPartyDeviceNumberOfButtonsPart.NumberOfButtons\x12\x91\x01\n\x0c\x63\x61pabilities\x18\x65 \x03(\x0e\x32{.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device.ThirdPartyDeviceNumberOfButtonsPart.Capability\x1a\xe7\x01\n+ThirdPartyDeviceNumberOfButtonsPartSettings\x12\xa1\x01\n\x11number_of_buttons\x18\x01 \x01(\x0e\x32\x80\x01.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device.ThirdPartyDeviceNumberOfButtonsPart.NumberOfButtonsH\x00\x88\x01\x01\x42\x14\n\x12_number_of_buttons\"J\n\nCapability\x12\x1a\n\x16\x43\x41PABILITY_UNSPECIFIED\x10\x00\x12 \n\x1c\x43\x41PABILITY_NUMBER_OF_BUTTONS\x10\x01\"\x86\x01\n\x0fNumberOfButtons\x12!\n\x1dNUMBER_OF_BUTTONS_UNSPECIFIED\x10\x00\x12\x19\n\x15NUMBER_OF_BUTTONS_ONE\x10\x01\x12\x19\n\x15NUMBER_OF_BUTTONS_TWO\x10\x02\x12\x1a\n\x16NUMBER_OF_BUTTONS_FOUR\x10\x03\x42R\nKsystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_deviceP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_device.third_party_device_number_of_buttons_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nKsystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.third_party_deviceP\001\272\002\000'
  _globals['_THIRDPARTYDEVICENUMBEROFBUTTONSPART']._serialized_start=272
  _globals['_THIRDPARTYDEVICENUMBEROFBUTTONSPART']._serialized_end=1233
  _globals['_THIRDPARTYDEVICENUMBEROFBUTTONSPART_THIRDPARTYDEVICENUMBEROFBUTTONSPARTSETTINGS']._serialized_start=789
  _globals['_THIRDPARTYDEVICENUMBEROFBUTTONSPART_THIRDPARTYDEVICENUMBEROFBUTTONSPARTSETTINGS']._serialized_end=1020
  _globals['_THIRDPARTYDEVICENUMBEROFBUTTONSPART_CAPABILITY']._serialized_start=1022
  _globals['_THIRDPARTYDEVICENUMBEROFBUTTONSPART_CAPABILITY']._serialized_end=1096
  _globals['_THIRDPARTYDEVICENUMBEROFBUTTONSPART_NUMBEROFBUTTONS']._serialized_start=1099
  _globals['_THIRDPARTYDEVICENUMBEROFBUTTONSPART_NUMBEROFBUTTONS']._serialized_end=1233
# @@protoc_insertion_point(module_scope)
