syntax = "proto3";

package systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device;

import "systems/ajax/api/ecosystem/v2/commonmodels/device/common/associated_member_part.proto";
import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/arm_prevention_override_permissions_part.proto";
import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/common_manage_button_part.proto";
import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_battery.proto";
import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_siren_triggers.proto";
import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/associated_group_id.proto";
import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/assigned_extender_part.proto";
import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/bypass_part.proto";
import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/cms_device_index_part.proto";
import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_migration_status_part.proto";
import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_profile_part.proto";
import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_common_capabilities_part.proto";
import "systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_telemetry_part.proto";

option java_multiple_files = true;
option java_package = "systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device";
option swift_prefix = "";

message SpaceControl {
  reserved 2;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceProfilePart device_profile_part = 1;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.AssignedExtenderPart assigned_extender_part = 3;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.CmsDeviceIndexPart cms_device_index_part = 4;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.BypassPart bypass_part = 5;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceMigrationStatusPart device_migration_status_part = 6;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceBatteryWithoutCharging device_battery = 7;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.SirenTriggers siren_triggers = 8;
  .systems.ajax.api.ecosystem.v2.commonmodels.device.common.AssociatedMemberPart associated_member_part = 9;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.ArmPreventionOverridePermissionsPart arm_prevention_override_permissions_part = 10;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.AssociatedGroupId associated_group_id = 11;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.CommonManageButtonPart common_button_part = 12;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceCommonCapabilitiesPart device_common_capabilities_part = 13;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceTelemetryPart device_telemetry_part = 14;
}

message SpaceControlS {
  reserved 2;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceProfilePart device_profile_part = 1;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.AssignedExtenderPart assigned_extender_part = 3;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.CmsDeviceIndexPart cms_device_index_part = 4;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.BypassPart bypass_part = 5;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceMigrationStatusPart device_migration_status_part = 6;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceBatteryWithoutCharging device_battery = 7;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.SirenTriggers siren_triggers = 8;
  .systems.ajax.api.ecosystem.v2.commonmodels.device.common.AssociatedMemberPart associated_member_part = 9;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.ArmPreventionOverridePermissionsPart arm_prevention_override_permissions_part = 10;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.AssociatedGroupId associated_group_id = 11;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.CommonManageButtonPart common_button_part = 12;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceCommonCapabilitiesPart device_common_capabilities_part = 13;
  .systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceTelemetryPart device_telemetry_part = 14;
}
