# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/third_party_device_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/third_party_device_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nOsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/third_party_device_type.proto\x12\x31systems.ajax.api.ecosystem.v2.hubsvc.commonmodels\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto*\xef\x04\n\x14ThirdPartyDeviceType\x12\'\n#THIRD_PARTY_DEVICE_TYPE_UNSPECIFIED\x10\x00\x12,\n(THIRD_PARTY_DEVICE_TYPE_OPENING_DETECTOR\x10\x01\x12)\n%THIRD_PARTY_DEVICE_TYPE_TILT_DETECTOR\x10\x02\x12+\n\'THIRD_PARTY_DEVICE_TYPE_MOTION_DETECTOR\x10\x03\x12\x30\n,THIRD_PARTY_DEVICE_TYPE_GLASS_BREAK_DETECTOR\x10\x04\x12*\n&THIRD_PARTY_DEVICE_TYPE_SHOCK_DETECTOR\x10\x05\x12\'\n#THIRD_PARTY_DEVICE_TYPE_CO_DETECTOR\x10\x06\x12*\n&THIRD_PARTY_DEVICE_TYPE_SMOKE_DETECTOR\x10\x07\x12)\n%THIRD_PARTY_DEVICE_TYPE_HEAT_DETECTOR\x10\x08\x12+\n\'THIRD_PARTY_DEVICE_TYPE_FREEZE_DETECTOR\x10\t\x12*\n&THIRD_PARTY_DEVICE_TYPE_FLOOD_DETECTOR\x10\n\x12\"\n\x1eTHIRD_PARTY_DEVICE_TYPE_KEYFOB\x10\x0b\x12\"\n\x1eTHIRD_PARTY_DEVICE_TYPE_CUSTOM\x10\x0c\x12)\n%THIRD_PARTY_DEVICE_TYPE_FIRE_DETECTOR\x10\rBA\n1systems.ajax.api.ecosystem.v2.hubsvc.commonmodelsP\x01\xba\x02\tCommonHubb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.third_party_device_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1systems.ajax.api.ecosystem.v2.hubsvc.commonmodelsP\001\272\002\tCommonHub'
  _globals['_THIRDPARTYDEVICETYPE']._serialized_start=202
  _globals['_THIRDPARTYDEVICETYPE']._serialized_end=825
# @@protoc_insertion_point(module_scope)
