# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/glass_protect.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/glass_protect.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_chimes_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_device_dot_common_dot_device__chimes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/glass_protect.proto\x12\x38systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device\x1aSsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_chimes.proto\"t\n\x0cGlassProtect\x12\x64\n\rdevice_chimes\x18\x01 \x01(\x0b\x32M.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceChimes\"u\n\rGlassProtectS\x12\x64\n\rdevice_chimes\x18\x01 \x01(\x0b\x32M.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceChimes\"y\n\x11GlassProtectFibra\x12\x64\n\rdevice_chimes\x18\x01 \x01(\x0b\x32M.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceChimesB?\n8systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.deviceP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.glass_protect_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n8systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.deviceP\001\272\002\000'
  _globals['_GLASSPROTECT']._serialized_start=223
  _globals['_GLASSPROTECT']._serialized_end=339
  _globals['_GLASSPROTECTS']._serialized_start=341
  _globals['_GLASSPROTECTS']._serialized_end=458
  _globals['_GLASSPROTECTFIBRA']._serialized_start=460
  _globals['_GLASSPROTECTFIBRA']._serialized_end=581
# @@protoc_insertion_point(module_scope)
