# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/z_wave_device.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/z_wave_device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_profile_part_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_device_dot_common_dot_device__profile__part__pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.z_wave_device import z_wave_device_clusters_part_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_device_dot_z__wave__device_dot_z__wave__device__clusters__part__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/z_wave_device.proto\x12\x38systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device\x1aYsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_profile_part.proto\x1ahsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/z_wave_device/z_wave_device_clusters_part.proto\"\x85\x02\n\x0bZWaveDevice\x12o\n\x13\x64\x65vice_profile_part\x18\x01 \x01(\x0b\x32R.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceProfilePart\x12\x84\x01\n\x1bz_wave_device_clusters_part\x18\x02 \x01(\x0b\x32_.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.z_wave_device.ZWaveDeviceClustersPartB?\n8systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.deviceP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.z_wave_device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n8systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.deviceP\001\272\002\000'
  _globals['_ZWAVEDEVICE']._serialized_start=336
  _globals['_ZWAVEDEVICE']._serialized_end=597
# @@protoc_insertion_point(module_scope)
