# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/rangeextender/main_channel_connection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/rangeextender/main_channel_connection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\ndsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/rangeextender/main_channel_connection.proto\x12\x46systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.rangeextender\"\xea\x02\n\x19MainChannelConnectionPart\x12\xa5\x01\n\x1emain_channel_connection_status\x18\x01 \x01(\x0e\x32}.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.rangeextender.MainChannelConnectionPart.MainChannelConnectionStatus\"\xa4\x01\n\x1bMainChannelConnectionStatus\x12.\n*MAIN_CHANNEL_CONNECTION_STATUS_UNSPECIFIED\x10\x00\x12*\n&MAIN_CHANNEL_CONNECTION_STATUS_OFFLINE\x10\x01\x12)\n%MAIN_CHANNEL_CONNECTION_STATUS_ONLINE\x10\x02\x42P\nFsystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.rangeextenderP\x01\xba\x02\x03Hubb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.rangeextender.main_channel_connection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nFsystems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.rangeextenderP\001\272\002\003Hub'
  _globals['_MAINCHANNELCONNECTIONPART']._serialized_start=177
  _globals['_MAINCHANNELCONNECTIONPART']._serialized_end=539
  _globals['_MAINCHANNELCONNECTIONPART_MAINCHANNELCONNECTIONSTATUS']._serialized_start=375
  _globals['_MAINCHANNELCONNECTIONPART_MAINCHANNELCONNECTIONSTATUS']._serialized_end=539
# @@protoc_insertion_point(module_scope)
